name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  global_env: global

jobs:
  sys_info:
    runs-on: windows-latest
    env:
      local_env: $env:GITHUB_JOB
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          pwd
          ls
      - name: print env
        run: env
      
  env:
    runs-on: windows-latest
    env:
      local_env: job_print_env
    
    steps:
      - uses: actions/checkout@v3
    
      - name: print env
        run: env
    
