name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  global_env: global

jobs:
  sys_info:
    runs-on: windows-latest
    env:
      local_env: ${{ github.job }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: working directory
        run: |
          pwd
          ls
      - name: print env
        run: env
      - name : check tools
        run: g++ -v
      
  build:
    runs-on: windows-latest
    needs: [sys_info]
   # env:
    #  local_env: job_print_env
    
    steps:
      - uses: actions/checkout@v3
    
      - name: build
        run: g++ main.cpp -o app_windows
          
        
  test:
    runs-on: windows-latest
    needs: [sys_info, build]
    steps:
      - name: run_test
        run: sleep 20
  #export:
    #runs-on: windows-latest
    
  
